### ISSUE TITLE
Quake1 tries to use the folder ApplicationSupport instead of Application Support

### ISSUE THREAD

**Issue by mikezila** [emctague/quake-mac-builder#1]
Title says it all. When running the app bundle you get a button that opens a finder window to slap in your .pak files, but it makes the folder in the wrong place.

**Comment by emctague** [comment]
Hi @mikezila does this break anything for you? On my system ApplicationSupport came symlinked to Application Support, I assume by default.

**Comment by mikezila** [comment]
It's not a symlink on my system, it's a normal folder that wasn't present before with just your quake bundle's stuff in it. I checked my wife's and work's Macs as well and there's no symlink on any of them in the user or global Library folders. All systems on Big Sur.

**Comment by emctague** [comment]
Odd, my system in particular must have had that symlink made by some tool. I'll adjust it to use application support with a space.

**Comment by emctague** [comment]
A new release should appear in at most 10 mins. that changes this.

**Comment by TerranceWolfe** [comment]
roger that
